apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-queue-handler
  labels:
    component: backend-queue-handler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: backend-queue-handler
  template:
    metadata:
      name: backend-queue-handler
      labels:
        component: backend-queue-handler
    spec:
      containers:
        - name: backend-queue-handler
          image: ipakeev/words-backend:dev
          env:
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_EXCHANGE
              value: words
            - name: RABBIT_ROUTING_KEY
              value: english
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: PYTHONUNBUFFERED
              value: "1"
          command:
            - python
            - manage.py
            - get_words_from_bot
          volumeMounts:
            - mountPath: /app/backend
              name: backend-code
      volumes:
        - name: backend-code
          hostPath:
            path: /dev/words/backend