# Generated by Django 4.1.3 on 2022-12-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.CharField(max_length=128, verbose_name="Оригинал")),
                (
                    "translation",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Перевод"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово",
                "verbose_name_plural": "Слова",
            },
        ),
    ]
