apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    component: volume
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"