apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
  labels:
    component: backend-migrations
spec:
  template:
    metadata:
      name: backend-migrations
      labels:
        component: backend-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: backend-migrations
          image: ipakeev/words-backend:dev
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
          command:
            - python
            - manage.py
            - migrate
          volumeMounts:
            - mountPath: /app/backend
              name: backend-code
      volumes:
        - name: backend-code
          hostPath:
            path: /dev/words/backend