apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  selector:
    component: rabbitmq
  ports:
    - port: 5672
      targetPort: rabbitmq
      name: rabbitmq